# -*- coding: utf-8 -*-

"""

NETZWERK
Computer network renderer
https://github.com/pleiszenburg/netzwerk

	src/netzwerk/const.py: Konstante Werte

	Copyright (C) 2017 Sebastian M. Ernst <ernst@pleiszenburg.de>

<LICENSE_BLOCK>
The contents of this file are subject to the GNU Lesser General Public License
Version 2.1 ("LGPL" or "License"). You may not use this file except in
compliance with the License. You may obtain a copy of the License at
https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
https://github.com/pleiszenburg/netzwerk/blob/master/LICENSE

Software distributed under the License is distributed on an "AS IS" basis,
WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License for the
specific language governing rights and limitations under the License.
</LICENSE_BLOCK>

"""


# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# KONSTANTEN
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

KEY_A = 'A'
KEY_ADRESSE = 'ADRESSE'
KEY_ANSCHLUESSE = 'ANSCHLUESSE'
KEY_ARBEITSPLATZ = 'ARBEITSPLATZ'
KEY_AUSGAENGE = 'AUSGAENGE'
KEY_B = 'B'
KEY_ART = 'ART'
KEY_BETRIEBSSYSTEM = 'BETRIEBSSYSTEM'
KEY_BEZEICHNUNG = 'BEZEICHNUNG'
KEY_BREITE = 'BREITE'
KEY_BAUM = 'BAUM'
KEY_CAT5 = 'CAT5'
KEY_CAT7 = 'CAT7'
KEY_COMPUTER = 'COMPUTER'
KEY_DARSTELLUNG = 'DARSTELLUNG'
KEY_DHCP = 'DHCP'
KEY_DOSE = 'DOSE'
KEY_DOSEN = 'DOSEN'
KEY_DOSENEBENE = 'DOSENEBENE'
KEY_DRUCKER = 'DRUCKER'
KEY_ELTERN = 'ELTERN'
KEY_ETHERNET = 'ETHERNET'
KEY_FARBE = 'FARBE'
KEY_FIREWIRE = 'FIREWIRE'
KEY_FIRMWARE = 'FIRMWARE'
KEY_FRONT = 'FRONT'
KEY_GETRENNT = 'GETRENNT'
KEY_GLOBAL = 'GLOBAL'
KEY_HAUS = 'HAUS'
KEY_HIERARCHIEEBENE = 'HIERARCHIEEBENE'
KEY_HINTERGRUNDFARBE = 'HINTERGRUNDFARBE'
KEY_HOEHE = 'HOEHE'
KEY_HORIZONTAL = 'HORIZONTAL'
KEY_HUB = 'HUB'
KEY_INTER = 'INTER'
KEY_IPV4 = 'IPV4'
KEY_IPV6 = 'IPV6'
KEY_KABEL = 'KABEL'
KEY_KATEGORIE = 'KATEGORIE'
KEY_KINDER = 'KINDER'
KEY_KLEMME = 'KLEMME'
KEY_KNICKE = 'KNICKE'
KEY_KOMPONENTE = 'KOMPONENTE'
KEY_KOMPONENTEN = 'KOMPONENTEN'
KEY_KOMPONENTENEBENE = 'KOMPONENTENEBENE'
KEY_KOPFLOS = 'KOPFLOS'
KEY_LINIE = 'LINIE'
KEY_LINKS = 'LINKS',
KEY_LOCH = 'LOCH'
KEY_MAC = 'MAC'
KEY_MASKE = 'MASKE'
KEY_MAX = 'MAX'
KEY_META = 'META'
KEY_MIN = 'MIN'
KEY_NAME = 'NAME'
KEY_NUMMER = 'NUMMER'
KEY_OBEN = 'OBEN'
KEY_ORIENTIERUNG = 'ORIENTIERUNG'
KEY_ORT = 'ORT'
KEY_PASSIV = 'PASSIV'
KEY_PATCHFELD = 'PATCHFELD'
KEY_POSITION = 'POSITION'
KEY_RADIUS = 'RADIUS'
KEY_RECHTS = 'RECHTS'
KEY_PREFIX = 'PREFIX'
KEY_RAUM = 'RAUM'
KEY_RUECKSEITE = 'RUECKSEITE'
KEY_SCHNITTSTELLE = 'SCHNITTSTELLE'
KEY_SCHNITTSTELLEN = 'SCHNITTSTELLEN'
KEY_SCHRIFTGROESSE = 'SCHRIFTGROESSE'
KEY_SERIENNUMMER = 'SERIENNUMMER'
KEY_SMARTPHONE = 'SMARTPHONE'
KEY_STANDORT = 'STANDORT'
KEY_STECKER = 'STECKER'
KEY_SUBNETZMASKE = 'SUBNETZMASKE'
KEY_SUFFIX = 'SUFFIX'
KEY_SVG = 'SVG'
KEY_SWITCH = 'SWITCH'
KEY_SWITCHES = 'SWITCHES'
KEY_SWITCHEBENE = 'SWITCHEBENE'
KEY_TEXT = 'TEXT'
KEY_TYP = 'TYP'
KEY_UNBEKANNT = 'UNBEKANNT'
KEY_UNDEFINIERT = 'UNDEFINIERT'
KEY_UNTEN = 'UNTEN'
KEY_UNTERBRECHUNG_MIN = 'UNTERBRECHUNG_MIN'
KEY_UNTERBRECHUNG_MAX = 'UNTERBRECHUNG_MAX'
KEY_USB = 'USB'
KEY_VERBINDUNG = 'VERBINDUNG'
KEY_VERBINDUNGEN = 'VERBINDUNGEN'
KEY_VERTIKAL = 'VERTIKAL'
KEY_VORBEREITET = 'VORBEREITET'
KEY_VORLAGE = 'VORLAGE'
KEY_VORLAGEN = 'VORLAGEN'
KEY_WIFI = 'WIFI'
KEY_X = 'X'
KEY_X1 = 'X1'
KEY_X2 = 'X2'
KEY_Y = 'Y'
KEY_Y1 = 'Y1'
KEY_Y2 = 'Y2'

PARAM_EBENEN = [KEY_GLOBAL, KEY_STANDORT, KEY_HAUS, KEY_RAUM]

PARAM_ABSTAND = 10.0
PARAM_ABSTAND_KLEIN = 3.0
PARAM_COMPUTER_BREITE = 200.0
PARAM_COMPUTER_FARBE = '#C0C0C0'
PARAM_ETHERNET_SCHRIFTGROESSE = 10.0
PARAM_ETHERNETPASSIV_BREITE = 24.0
PARAM_ETHERNETPASSIV_HOEHE = PARAM_ETHERNET_SCHRIFTGROESSE + 4.0 * PARAM_ABSTAND_KLEIN
PARAM_ETHERNET_BREITE = 90.0
PARAM_ETHERNET_HOEHE = 30.0
PARAM_ETHERNET_FARBE = '#DDDDDD'
PARAM_LOCH_FARBE = '#FFDDDD'
PARAM_VORBEREITET_FARBE = '#FF8888'
PARAM_DOSE_BREITE = PARAM_ETHERNETPASSIV_BREITE
PARAM_DOSE_HOEHE = PARAM_ETHERNETPASSIV_HOEHE
PARAM_NAME_SCHRIFTGROESSE = 14.0
PARAM_RAUM_SCHRIFTGROESSE = 18.0
PARAM_TEXT_FARBE = '#000000'
PARAM_TEXT_FONT = 'Carlito'
PARAM_RJ45M_BREITE = 4.0
PARAM_RJ45M_FARBE = '#FF0000'
PARAM_RJ45W_R = 5.0
PARAM_RJ45W_FARBE = '#000000'
PARAM_UTP_BREITE = 2.0
PARAM_UTP_FARBE = '#FF0000'

DEFAULT_IPV4 = [255, 255, 255, 255]
DEFAULT_SUBNETZMASKE = [255, 255, 255, 0]
DEFAULT_MAC = [0xff, 0xff, 0xff, 0xff, 0xff, 0xff]
